FROM node:18-alpine

# ไปที่ app directory ใน node image
WORKDIR /app

# Copy package.json เข้า image
COPY package*.json ./
# Install app dependencies
# RUN npm ci
# RUN npm install --package-lock-only
# RUN npm update
RUN npm update -g npm

RUN npm install --force
# RUN npm install
# Copy ไฟล์มั้หมด ได้แก่ public, src folder เข้าไป
COPY . .

EXPOSE 3000

RUN npm run build
#สั่ง npm start เพื่อ start React App
CMD [ "npm", "start" ]