version: "3.9"
services:
  showweb:
    container_name: showweb
    image: myreact
    ports:
      - "8001:3000" #server
      - "80:8001" #server

  backend:
    container_name: backend
    image: mydb
    ports:
      - "8000:8000"
      - "8101:443"
    depends_on:
      - showweb
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=db_host
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WDS_SOCKET_PORT=443
      - SECRET_KEY=django-insecure-fyr$qmpwlyhi6f_xnpliot%q+d+3fx)y0pyy@$u-#yf4&*+!fz
      - PEPPER=kmitl
      - EMAIL_HOST_USER=mcqa.system@gmail.com
      - EMAIL_HOST_PASSWORD=tubh bawz zcqy bqdg
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    container_name: redis
    # ports:
    #   - "6379:6379"

  celery:
    container_name: celery
    restart: always
    image: celery
    ports:
      - "6379:6379"
    depends_on:
      - postgres
      - redis
      - backend
volumes:
  static_volume: {}
  postgres_data: {}