version: "3.3"
services:
    showweb:
        container_name: showweb
        image: myreact
        ports:
        # - "80:3000"
        - "8001:8000"
        
    backend:
      container_name: backend
      image: mydb
      command: python ./manage.py runserver 0.0.0.0:8000
      ports:
        - 8101:8000
      depends_on:
        - postgres
      environment:
        - POSTGRES_HOST=db_host
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_DB=mcqas
        - SECRET_KEY=django-insecure-fyr$qmpwlyhi6f_xnpliot%q+d+3fx)y0pyy@$u-#yf4&*+!fz
        - PEPPER=kmitl
        - EMAIL_HOST_USER=mcqa.system@gmail.com
        - EMAIL_HOST_PASSWORD=tubh bawz zcqy bqdg

    postgres:
      container_name: postgres
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_DB=mcqas
      volumes:
        - ./postgres:/var/lib/postgresql/data

    redis:build: 
      image: redis:alpine
      container_name: redis

    celery:
      container_name: celery
      restart: always
      build: .
      command: celery -A mysite worker --loglevel=info
      valumes:
        - :/code      
      depends_on:
        - postgres
        - redis
        - backend
      links:
        - postgres

volumes:
    pgdata:

