version: "3.9"
services:
  showweb:
    container_name: showweb
    image: myreact
    ports:
      - "10.220.66.101:443:3000"

  redis:
      restart: unless-stopped
      container_name: redis
      image: redis:7.0.5-alpine 
      ports:
        - "6380:6380"

  postgresdb:
    container_name: postgres
    image: postgres 
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
      - POSTGRES_PORT=5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/mcqas.sql:/docker-entrypoint-initdb.d/mcqas.sql

  backend:
    container_name: backend
    image: mydb
    ports:
      - "10.220.66.101:80:8000"
    depends_on:
      - showweb
      - postgresdb
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - WDS_SOCKET_PORT=300
      - SECRET_KEY=django-insecure-fyr$qmpwlyhi6f_xnpliot%q+d+3fx)y0pyy@$u-#yf4&*+!fz
      - PEPPER=kmitl
      - EMAIL_HOST_USER=mcqa.system@gmail.com
      - EMAIL_HOST_PASSWORD=tubh bawz zcqy bqdg
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0

  celerybeat:
    container_name: celerybeat
    restart: always
    image: celery
    depends_on:
      - postgresdb
      - redis
      - backend
    command: celery -A mysite beat --loglevel=INFO
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0

  celeryworker:
    container_name: celeryworker
    restart: always
    image: celery
    depends_on:
      - postgresdb
      - redis
      - backend
    command: celery -A mysite worker --loglevel=INFO
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0