version: "3.9"
services:
  showweb:
    container_name: showweb
    image: myreact
    ports:
      - "80:80"

  redis:
      restart: unless-stopped
      container_name: redis
      image: redis:7.0.5-alpine 
      ports:
        - "6380:6380"

  backend:
    container_name: backend
    image: mydb
    ports:
      - "443:443"
    depends_on:
      - showweb
      - postgres
    environment:
      - POSTGRES_HOST=db_host
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - WDS_SOCKET_PORT=443
      - SECRET_KEY=django-insecure-fyr$qmpwlyhi6f_xnpliot%q+d+3fx)y0pyy@$u-#yf4&*+!fz
      - PEPPER=kmitl
      - EMAIL_HOST_USER=mcqa.system@gmail.com
      - EMAIL_HOST_PASSWORD=tubh bawz zcqy bqdg
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0

  postgres:
      container_name: postgres
      image: postgres 
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_DB=mcqas
      volumes:
        - ./postgres:/var/lib/postgresql/data

  celery:
    container_name: celery
    restart: always
    image: celery
    depends_on:
      - postgres
      - redis
      - backend
