version: "3.9"
services:
  showweb:
    container_name: showweb
    image: myreact
    ports:
      - "10.220.66.101:443:3000"

  redis:
      restart: unless-stopped
      container_name: redis
      hostname: redis
      image: redis:7.0.5-alpine
      ports:
        - "6380:6379"

  postgresdb:
    container_name: postgres
    image: postgres:alpine3.18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
      - POSTGRES_PORT=5432
    volumes:
      - ./database/mcqas.sql:/docker-entrypoint-initdb.d/mcqas.sql
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kmitl.ac.th
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/root/.pgadmin
    depends_on:
      - postgresdb

  backend:
    container_name: backend
    image: mydb
    ports:
      - "10.220.66.101:80:8000"
    depends_on:
      - showweb
      - postgresdb
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mcqas
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - WDS_SOCKET_PORT=3000
      - SECRET_KEY=django-insecure-fyr$qmpwlyhi6f_xnpliot%q+d+3fx)y0pyy@$u-#yf4&*+!fz
      - PEPPER=kmitl
      - EMAIL_HOST_USER=mcqa.system@gmail.com
      - EMAIL_HOST_PASSWORD=tubh bawz zcqy bqdg
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0

volumes:
  postgres-data:
  pgadmin-data: