CREATE TABLE "User" (
  "UserID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email" varchar(255),
  "FullName" text,
  "Password" varchar(255),
  "Salt" varchar(64),
  "GoogleId" text,
  "Job" text,
  "Department" text,
  "Faculty" text,
  "Workplace" text,
  "Tel" varchar(10),
  "Usageformat" varchar(10),
  "ImgE_KYC_path" text,
  "E_KYC" varchar(20),
  "TypesID" int,
  "CreateTimeUser" timestamp with time zone
);

CREATE TABLE "Type" (
  "TypesID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TypesName" varchar(50),
  "LimitSubject" int,
  "LimitExam" int,
  "LimitQue" int
);

CREATE TABLE "Request" (
  "RequestID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "ImgRequest_path" text,
  "Notes" text,
  "Status_Request" text
);

CREATE TABLE "Subject" (
  "SubID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "SubjectID" varchar(30),
  "SubjectName" varchar(100),
  "Year" varchar(10),
  "Semester" varchar(10),
  "StatusSubject" text,
  "DeleteTimeSubject" timestamp with time zone,
  "CreateTimeSubject" timestamp with time zone
);

CREATE TABLE "Exam" (
  "ExamID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SubID" int,
  "ExamName" text,
  "ExamNo" int,
  "NumberofExams" int,
  "NumberofExamSets" int,
  "AnswerSheetFormat" text,
  "ImgAnswerSheetformat_path" text,
  "Std_csv_path" text,
  "Result_csv_path" text,
  "Analysis_csv_path" text,
  "SequenceSteps" text,
  "ShowScores" int,
  "SendEmail" int,
  "StatusExam" text,
  "DeleteTimeExam" timestamp with time zone,
  "CreateTimeExam" timestamp with time zone
);

CREATE TABLE "ExamAnswers" (
  "ExamAnswersID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ExamID" int,
  "ExamNoAnswers" varchar(2),
  "ScoringCriteria" text,
  "ChoiceAnswers" text,
  "PapeAns_path" text
);

CREATE TABLE "ExamInformation" (
  "ExamInfoID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ExamID" int,
  "StdID" varchar(20),
  "StdEmail" varchar(255),
  "SubjectIDStd" varchar(20),
  "ExamSeatNumber" varchar(20),
  "SetExamInfo" int,
  "Section" varchar(20),
  "Score" int,
  "Correct" int,
  "Wrong" int,
  "Unresponsive" int,
  "ItemAnalysis" text,
  "AnsChoiceStd" text,
  "ImgAnsStd_path" text,
  "ErrorsType" text,
  "CreateTimeExaminfo" timestamp with time zone
);

CREATE TABLE "Chapter" (
  "ChapterID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "NameChapter" text,
  "InfoChapter" text
);

CREATE TABLE "SubChapter" (
  "SubChapterID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ChapterID" int,
  "NumSubChapter" text,
  "NameSubChapter" text,
  "InfoSubChapter" text
);

CREATE TABLE "ChapterAnswer" (
  "ChapterAnswerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ExamAnswersID" int,
  "SubChapterID" int,
  "AnswerChapter" text
);

CREATE TABLE "QueSheet" (
  "QueSheetID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "QueSheetName" text,
  "QueSheetTopicName" text,
  "DetailsLineOne" text,
  "DetailsLineTwo" text,
  "ImgQueSheet_path" text,
  "ResultPart1_csv_path" text,
  "ResultPart2_csv_path" text,
  "DateTimeStart" timestamp with time zone,
  "DateTimeEnd" timestamp with time zone,
  "SequenceSteps" Text,
  "StatusQueSheet" text,
  "DeleteTimeQueSheet" timestamp with time zone,
  "CreateTimeQueSheet" timestamp with time zone
);

CREATE TABLE "QueHeadDetails" (
  "QueHeadDetailsID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QueSheetID" int,
  "QueHead1" text,
  "QueHead2" text,
  "QueHead3" text,
  "QueHead4" text,
  "QueHead5" text
);

CREATE TABLE "QueTopicDetails" (
  "QueTopicDetailsID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QueSheetID" int,
  "QueTopicDetails" text,
  "QueTopicFormat" text
);

CREATE TABLE "QueInformation" (
  "QueInfoID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QueSheetID" int,
  "AnsQueHead" text,
  "AnsQueTopic" text,
  "AnsOther" text,
  "Additionalsuggestions" text,
  "ImgAnsStd_path" text,
  "Status_QueInfo" text,
  "ErrorsType" text,
  "CreateTimeQueSheetinfo" timestamp with time zone
);

ALTER TABLE "User" ADD FOREIGN KEY ("TypesID") REFERENCES "Type" ("TypesID");

ALTER TABLE "Request" ADD FOREIGN KEY ("UserID") REFERENCES "User" ("UserID");

ALTER TABLE "Subject" ADD FOREIGN KEY ("UserID") REFERENCES "User" ("UserID");

ALTER TABLE "Exam" ADD FOREIGN KEY ("SubID") REFERENCES "Subject" ("SubID");

ALTER TABLE "ExamAnswers" ADD FOREIGN KEY ("ExamID") REFERENCES "Exam" ("ExamID");

ALTER TABLE "ExamInformation" ADD FOREIGN KEY ("ExamID") REFERENCES "Exam" ("ExamID");

ALTER TABLE "Chapter" ADD FOREIGN KEY ("UserID") REFERENCES "User" ("UserID");

ALTER TABLE "SubChapter" ADD FOREIGN KEY ("ChapterID") REFERENCES "Chapter" ("ChapterID");

ALTER TABLE "ChapterAnswer" ADD FOREIGN KEY ("ExamAnswersID") REFERENCES "ExamAnswers" ("ExamAnswersID");

ALTER TABLE "ChapterAnswer" ADD FOREIGN KEY ("SubChapterID") REFERENCES "SubChapter" ("SubChapterID");

ALTER TABLE "QueSheet" ADD FOREIGN KEY ("UserID") REFERENCES "User" ("UserID");

ALTER TABLE "QueHeadDetails" ADD FOREIGN KEY ("QueSheetID") REFERENCES "QueSheet" ("QueSheetID");

ALTER TABLE "QueTopicDetails" ADD FOREIGN KEY ("QueSheetID") REFERENCES "QueSheet" ("QueSheetID");

ALTER TABLE "QueInformation" ADD FOREIGN KEY ("QueSheetID") REFERENCES "QueSheet" ("QueSheetID");

ALTER DATABASE mcqas SET TIMEZONE TO 'Asia/Bangkok';

INSERT INTO "Type" ("TypesName", "LimitSubject", "LimitExam", "LimitQue") VALUES 
('Admin', 1000, 1000, 1000),
('Internaluser', 30, 5, 30),
('Externalusers', 5, 5, 5);

INSERT INTO "User" ("Email", "FullName", "Password", "Salt", "GoogleId", "Job", "Department", "Faculty", "Workplace", "Tel", "Usageformat", "ImgE_KYC_path", "E_KYC", "TypesID", "CreateTimeUser") VALUES 
(
  'admin@kmitl.ac.th',
  'Admin',
  '$2b$12$7aTX7fzSJRyup4gtqh1ht.Y8EG0Czfz2aht7SXuRGcGG8n3BeJcdK',
  '$2b$12$7aTX7fzSJRyup4gtqh1ht.',
  'admin',
  'Admin',
  'วิศวกรรมคอมพิวเตอร์',
  'วิศวกรรมศาสตร์',
  'KMITL',
  '0917296297',
  '[1,1]',
  NULL,
  '1',
  CURRENT_TIMESTAMP,
  1
);