# Generated by Django 4.2.5 on 2023-12-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errorsanswersheet',
            fields=[
                ('errorsanssheetid', models.AutoField(db_column='ErrorsAnsSheetID', primary_key=True, serialize=False)),
                ('errorstdid', models.CharField(blank=True, db_column='ErrorStdID', max_length=20, null=True)),
                ('errorsubidstd', models.CharField(blank=True, db_column='ErrorSubIDStd', max_length=20, null=True)),
                ('errorexamseatnumber', models.CharField(blank=True, db_column='ErrorExamSeatNumber', max_length=20, null=True)),
                ('errorsetexaminfo', models.IntegerField(blank=True, db_column='ErrorSetExamInfo', null=True)),
                ('errorsection', models.CharField(blank=True, db_column='ErrorSection', max_length=20, null=True)),
                ('errorstype', models.TextField(blank=True, db_column='ErrorsType', null=True)),
                ('errorimgansstd_path', models.TextField(blank=True, db_column='ErrorImgAnsStd_path', null=True)),
            ],
            options={
                'db_table': 'ErrorsAnswerSheet',
                'managed': False,
            },
        ),
    ]
