# Generated by Django 4.2.5 on 2024-01-02 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_errorsanswersheet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Errorsanswersheet",
        ),
    ]
