# Generated by Django 4.2.5 on 2024-01-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_delete_errorsanswersheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "chapterid",
                    models.AutoField(
                        db_column="ChapterID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "namechapter",
                    models.TextField(blank=True, db_column="NameChapter", null=True),
                ),
                (
                    "infochapter",
                    models.TextField(blank=True, db_column="InfoChapter", null=True),
                ),
            ],
            options={
                "db_table": "Chapter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Chapteranswer",
            fields=[
                (
                    "chapteranswerid",
                    models.AutoField(
                        db_column="ChapterAnswerID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "answerchapter",
                    models.TextField(blank=True, db_column="AnswerChapter", null=True),
                ),
            ],
            options={
                "db_table": "ChapterAnswer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subchapter",
            fields=[
                (
                    "subchapterid",
                    models.AutoField(
                        db_column="SubChapterID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numsubchapter",
                    models.TextField(blank=True, db_column="NumSubChapter", null=True),
                ),
                (
                    "namesubchapter",
                    models.TextField(blank=True, db_column="NameSubChapter", null=True),
                ),
                (
                    "infosubchapter",
                    models.TextField(blank=True, db_column="InfoSubChapter", null=True),
                ),
            ],
            options={
                "db_table": "SubChapter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "typesid",
                    models.AutoField(
                        db_column="TypesID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "typesname",
                    models.CharField(
                        blank=True, db_column="TypesName", max_length=50, null=True
                    ),
                ),
                (
                    "limitsubject",
                    models.IntegerField(
                        blank=True, db_column="LimitSubject", null=True
                    ),
                ),
                (
                    "limitexam",
                    models.IntegerField(blank=True, db_column="LimitExam", null=True),
                ),
                (
                    "limitque",
                    models.IntegerField(blank=True, db_column="LimitQue", null=True),
                ),
            ],
            options={
                "db_table": "Type",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="Checkscore",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="Lessonanswer",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="Sublesson",
        ),
        migrations.AlterModelTable(
            name="examinformation",
            table="ExamInformation",
        ),
        migrations.AlterModelTable(
            name="queinformation",
            table="QueInformation",
        ),
    ]
